apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: access-logs-pvc
  namespace: keepcoding
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
